### ISSUE TITLE
Beta linter encounters nil pointer dereference with LocalRegistryImagePullSecret

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/replicated#123]
Linting
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kots.io/exclude: '{{repl or (eq Namespace (or (ConfigOption "namespace") Namespace)) (not HasLocalRegistry) }}'
  name: kotsadm-replicated-registry
  namespace: '{{repl or (ConfigOption "namespace") Namespace }}'
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: '{{repl LocalRegistryImagePullSecret}}'
```
with `--beta-linter` produces
```
RULE                TYPE     FILENAME                       LINE    MESSAGE
unable-to-render    error    cd4pe/regcred.yaml                                                                       at <LocalRegistryImagePullSecret>: error calling LocalRegistryImagePullSecret: runtime error: invalid memory address or nil pointer dereference
```
