### ISSUE TITLE
"installer create" doesn't return error message

### ISSUE THREAD

**Issue by BretFisher** [replicatedhq/replicated#186]
If I have a bad key or value in installer YAML, the Replicated Vendor Portal returns the error message, but all the CLI does is return an error code.

Suggested fix: have CLI return error messages from Replicated API to ease troubleshooting.

To reproduce:

1. Create an installer YAML where the version key is missing for a kurl addon. There is no linter (afaik) for kurl yaml, so I try to create a release by pasting it in Vendor Portal and get an error `spec/kotsadm must have required property 'version'`.

    ```yaml
    apiVersion: "cluster.kurl.sh/v1beta1"
    kind: "Installer"
    metadata: 
      name: "latest"
    spec: 
      kubernetes: 
        #    version: "latest"
      containerd: 
        version: "latest"
    
    ```
2. Do the same thing with CLI using something like `replicated installer create --yaml-file kurl-installer.yaml`

Result:

```text
  • Creating Installer ✗  
Error: POST https://api.replicated.com/vendor/v3/app/xxxxx/installer 500:
```

No error message is displayed.
