### ISSUE TITLE
Release notes lines beginning with hashes are stripped from the 

### ISSUE THREAD

**Issue by RobClenshaw** [replicatedhq/replicated#265]
If I try and put the release notes directly into the application.yaml file like this -

```
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: redgate-clone
spec:
  title: Redgate Clone
  icon: https://cloningcapability.z33.web.core.windows.net/redgate.png
  releaseNotes: |
    ## 1.0.54848
    #### Released on 2023-06-13

    ### Warnings

    ### Features

    ### Fixes
    * Reduced default CPU request for Oracle clones
    * Do stuff like `abc | def` or '
```
- and then I run a `replicated release create`, all the lines apart from the last two are stripped when I look at it in the vendor portal.
![image](https://github.com/replicatedhq/replicated/assets/10632166/955a59c4-b271-4e7b-96d1-cb2d6f87f151)
